version: "3"

services:
  maderas:
    container_name: MADERAS-NGINX
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8084:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.maderas.rule=Host(`maderas.devtr.es`)
      - traefik.http.routers.maderas.entrypoints=https
      - traefik.docker.network=traefik_default
      - traefik.http.routers.maderas.tls=true
      - traefik.http.routers.maderas.tls.certresolver=default
    networks:
      - frontend

networks:
  frontend:
    external:
      name: traefik_frontend
